Repository lenra-io/docs, pull requests merged in 2023-03, with the labels that each got.

#83 feat: Components page
  doc-deps.yml
  src/static/css/.components.css
  src/static/css/components/.tab-filter.css
  src/static/css/components/.tab.css
  src/static/css/page/references/components-api/components/index.css
  src/static/img/components/button.svg
  src/static/img/components/checkbox.svg
  src/static/img/components/container.svg
  src/static/img/components/dropdown-button.svg
  src/static/img/components/icon.svg
  src/static/img/components/image.svg
  src/static/img/components/menu-itel.svg
  src/static/img/components/menu.svg
  src/static/img/components/radio.svg
  src/static/img/components/slider.svg
  src/static/img/components/text-field.svg
  src/static/img/components/text.svg
  src/static/img/components/toggle.svg
  src/static/img/logo/black.svg
  src/static/js/filter.js
  src/views/references/components-api/components/index.pug
Labels: enhancement

#84 fix: Typo "optionnal"
  src/static/css/components/.properties-table.css
Labels: documentation

#85 feat: Crons
  src/markdown/features/crons.md
Labels: documentation

#87 fix: Contact link, home description, todo img & pug source path
  lesta.config.js
  src/markdown/guides/todo-list-app.md
  src/markdown/index.md
Labels: bug
